# Fase di build per React
FROM node:18-alpine AS build
WORKDIR /app

COPY ui/package*.json ./
RUN npm install
COPY ui/. ./
RUN npm run build

# Fase di deploy con Nginx
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
