server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  # Gestione SPA React
  location / {
    try_files $uri /index.html;
  }

  # Proxy per /api/jobs verso jobs-service
location /api/jobs/ {
    proxy_pass http://jobs-service:8080/jobs/;
}
  # Proxy per /api verso auth-service
  location /api/ {
    proxy_pass http://auth-service:3000/;
  }
}
